name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Test with Maven
        run: mvn -B test --file pom.xml
      - name: Build with Maven
        run: |
          mvn -B clean --file pom.xml
          mvn -B package --file pom.xml
